version: "3"

services:
  be:
    build:
      .
    ports:
      - 4567:4567
    environment:
      - NEO4J_PASS=${NEO4J_PASS}

  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASS}